buildscript {
    ext.kotlin_version = '1.9.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // START: FlutterFire Configuration
        classpath 'com.google.gms:google-services:4.3.15'
        // END: FlutterFire Configuration
        classpath 'com.android.tools.build:gradle:8.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
//릴리즈 apk 빌드 에러 추가
subprojects {
    afterEvaluate { project ->
        if (project.plugins.hasPlugin("com.android.application") ||
                project.plugins.hasPlugin("com.android.library")) {
            
            // Android 설정 통일
            project.android {
                compileSdkVersion 35
                buildToolsVersion "35.0.1"

                //Java 컴파일 타겟 11로 통일
                compileOptions {
                sourceCompatibility JavaVersion.VERSION_11
                targetCompatibility JavaVersion.VERSION_11
               }
            }

            // Kotlin jvmTarget 11 통일
            project.tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
                kotlinOptions {
                    jvmTarget = "11"
                }
            }
        }    
            //     // Release와 Debug 모두에 대해 설정
            //     buildTypes {
            //         release {
            //             minifyEnabled true
            //             shrinkResources true
            //         }
            //         debug {
            //             // 디버그용 설정 추가
            //             debuggable true
            //             applicationIdSuffix ".debug"
            //             versionNameSuffix "-debug"
            //         }
            //     }

    }
}


subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    namespace project.group
                }
            }
        }
    }
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
